#pragma once

#include "BoardPanel.h"
#include "HelpWindow.h"
#include "AboutWindow.h"
#include "Controller.h"
#include "SettingsWindow.h"
#include "Settings.h"
#include "IBoardUpdateCallback.h"

	/*
	Is a GUI container for frame, status bar and menu.
	*/
	class MainWindow : public IBoardUpdateCallback {
	public:
		MainWindow();

		/* Disable copy constructor and assignment operator*/
		MainWindow(const MainWindow& rhs) = delete;
		MainWindow& operator=(const MainWindow& rhs) = delete;

		~MainWindow();

	private:
		/*
		Show main menu
		*/
		void showMenu();

		/*
		Show help
		*/
		void showHelp();

		/*
		Show about
		*/
		void showAbout();

		/*
		Exit the process
		*/
		void exitProcess();

		/*
		Show setting window
		@return Setting that was generated by the user.
		*/
		Settings showSettings();

		/*
		Restart the current game. If any.
		*/
		void restartGame();

		virtual void onBoardUpdate() override;

		/*A mock when the user clicks the non existing status bar (we are running console)*/
		void getMenuClick();
		
		/*A mock status bar */
		char statusBar;

		BoardPanel* boardPanel;
		Controller* controller;
		
		SettingsWindow* settings;
		HelpWindow* help;
		AboutWindow* about;
	};

